# Generated by Django 5.0.3 on 2024-05-20 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_Bits',
        ),
    ]
