# Generated by Django 5.0.3 on 2024-04-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_id', models.CharField(max_length=20, unique=True)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('cour', models.CharField(max_length=100)),
                ('yearr', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
    ]
