# Generated by Django 5.0.3 on 2024-04-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentt',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='cour',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stud_id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='yearr',
            new_name='year',
        ),
    ]
