# Generated by Django 5.0.3 on 2024-04-29 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_rename_studentt_student_rename_cour_student_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_borrowed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='due_date_returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
