# Generated by Django 5.0.3 on 2024-04-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_student_date_borrowed_student_due_date_returned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='due_date_returned',
            new_name='date_returned',
        ),
    ]
