# Generated by Django 5.0.3 on 2024-04-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_rename_due_date_returned_student_date_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
