# Generated by Django 5.0.3 on 2024-05-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_student_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_returned',
        ),
        migrations.AlterField(
            model_name='student',
            name='date_borrowed',
            field=models.CharField(max_length=30),
        ),
    ]
